# Generated by Django 4.1.7 on 2023-03-24 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_categoty', models.CharField(max_length=100)),
                ('schedule_trip', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('payable', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('bus_name', models.CharField(max_length=255)),
                ('seats', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_bus', models.CharField(max_length=255)),
                ('depart', models.CharField(max_length=400)),
                ('destination', models.CharField(max_length=400)),
                ('dchedule_trip', models.DateTimeField()),
                ('fare', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
